"""Walk the reference_assets/ tree and emit a single LICENSES.md.

Groups clips by license so attribution duties are easy to satisfy.

Usage:
    python scripts/build_licenses_md.py
    python scripts/build_licenses_md.py --out docs/LICENSES.md
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REF_ROOT = REPO / "english" / "src" / "eng_tts" / "voices" / "reference_assets"
DEFAULT_OUT = REPO / "LICENSES.md"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--ref-root", type=Path, default=REF_ROOT)
    args = parser.parse_args()

    by_license: dict[str, list[dict]] = defaultdict(list)
    for manifest in sorted(args.ref_root.glob("*/manifest.json")):
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  skip {manifest}: {e}")
            continue
        by_license[data.get("license", "unknown")].append(data)

    lines: list[str] = []
    lines.append("# Voice reference clip licenses")
    lines.append("")
    lines.append("This file is auto-generated by `scripts/build_licenses_md.py`.")
    lines.append("")
    total = sum(len(v) for v in by_license.values())
    lines.append(f"Total ingested clips: **{total}**")
    lines.append("")

    for license_name in sorted(by_license):
        clips = by_license[license_name]
        lines.append(f"## {license_name} ({len(clips)} clip{'s' if len(clips) != 1 else ''})")
        lines.append("")
        if license_name.startswith("CC-BY"):
            lines.append("> Attribution **required** in any user-facing distribution.")
            lines.append("")
        for c in sorted(clips, key=lambda d: d.get("codename", "")):
            cn = c.get("codename", "?")
            lines.append(f"### {cn}")
            lines.append("")
            lines.append(f"- duration: {c.get('duration_s', '?')}s")
            lines.append(f"- language: {c.get('language', '?')}")
            if c.get("source_title"):
                lines.append(f"- source: {c['source_title']}")
            if c.get("source_url"):
                lines.append(f"- url: <{c['source_url']}>")
            if c.get("attribution_string"):
                lines.append(f"- attribution: {c['attribution_string']}")
            lines.append(f"- ingested: {c.get('ingested_at', '?')}")
            lines.append("")

    if not by_license:
        lines.append("_No reference clips ingested yet. Use `scripts/ingest_reference_voice.py`._")
        lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.out.relative_to(REPO)} ({total} clips, {len(by_license)} license group{'s' if len(by_license) != 1 else ''})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
